# code: language=ansible
---
- name: Add opendkim group
  ansible.builtin.group:
    name: "{{ opendkim_group }}"
    system: true
- name: Add opendkim user
  ansible.builtin.user:
    name: "{{ opendkim_user }}"
    group: "{{ opendkim_group }}"
    system: true
