# code: language=ansible
---
- name: OpenDKIM config directory
  ansible.builtin.file:
    path: "{{ opedkim_table_config_dir }}"
    state: directory
    owner: "{{ opendkim_user }}"
    group: "{{ opendkim_group }}"
    mode: "0755"
- name: OpenDKIM key directories
  ansible.builtin.file:
    path: "{{ opedkim_key_dir }}"
    state: directory
    owner: "{{ opendkim_user }}"
    group: "{{ opendkim_group }}"
    mode: "0700"
- name: Update OpenDKIM setting files
  ansible.builtin.template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
    mode: "0644"
  notify: Restart opendkim
- name: Create/Update OpenDKIM config table files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ opedkim_table_config_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - KeyTable
    - SigningTable
    - TrustedHosts
- name: Generate OpenDKIM keys
  ansible.builtin.include_tasks:
    file: domain_keys.yml
  loop: "{{ opedkim_domains | default([]) }}"
  loop_control:
    loop_var: opedkim_domain
- name: MTA alignment setting
  ansible.builtin.include_tasks:
    file: mta/{{ opendkim_mta }}.yml
