# code: language=ansible
---
- name: OpenDKIM key directories
  ansible.builtin.file:
    path: "{{ opedkim_key_dir }}"
    state: directory
    owner: "{{ opendkim_user }}"
    group: "{{ opendkim_group }}"
    mode: "0700"

# - name: Create OpenDKIM setting files
#   ansible.builtin.template:
#     src: "{{ item }}.j2"
#     dest: "{{ opendkim_config_dir }}/{{ item }}"
#     mode: "0644"
#   loop:
#     - TrustedHosts
#     - KeyTable
#     - SigningTable
#   notify: Restart opendkim
# - name: Generate OpenDKIM keys
#   ansible.builtin.include_tasks:
#     file: domain_key.yml
#   loop: "{{ opedkim_domains | default([]) }}"
#   loop_control:
#     loop_var: opedkim_domain
