# code: language=ansible
---
- name: Restart opendkim
  ansible.builtin.systemd_service:
    state: restarted
    name: opendkim
- name: Reload opendkim
  ansible.builtin.systemd_service:
    state: reloaded
    name: opendkim
- name: Restart postfix
  ansible.builtin.systemd_service:
    state: restarted
    name: postfix
