# code: language=ansible
---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
    - name: Update cache(yum)
      ansible.builtin.yum:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'yum'
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - common
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  post_tasks:
    - name: Send test mail
      community.general.mail:
        to: wate <pc.poisoning@gmail.com>
        from: role test <test@eample.com>
        subject: Ansible OpenDKIM role test mail({{ inventory_hostname }})
        body: Hello, this is OpenDKIM test mail.
