---
- name: Install Postfix
  ansible.builtin.apt:
    name: postfix
- name: Configuration OpenDKIM postfix milter
  ansible.builtin.blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} opendkim ANSIBLE MANAGED BLOCK"
    content: |
      {% for opendkim_postfix_setting in opendkim_postfix_cfg -%}
      {{ opendkim_postfix_setting.key }} = {{ opendkim_postfix_setting.value }}
      {% endfor %}
  notify: Restart postfix
